### PR TITLE
RES-433 Fixup namespace to utilize standalone htmresearch_core where …

### PR DESCRIPTION
**Pull request by oxtopus**
…appropriate

Companion PR to https://github.com/numenta/nupic.research.core/pull/12

### CODE REVIEW

**Comment by subutai** [comment]
Could you try running `py.test tests/layers/ tests/regions/ tests/algorithms/` on this branch?

**Comment by subutai** [comment]
Please ensure run_tests.sh passes with these changes before merging.

**Comment by oxtopus** [comment]
@subutai It all passes for me now.

**Comment by oxtopus** [comment]
@subutai I take that back.  They fail now after latest change to master.  Fixing...

**Comment by oxtopus** [comment]
We have success! https://ci.numenta.com/browse/BS-RS-20

**Comment by subutai** [comment]
🎆

**Pull request merged**
