### PR TITLE
RES-379: better distance metric

### PR DESCRIPTION
**Pull request by marionleborgne**
WIP

* added settings to turn on and off clustering + pick what TM cells to cluster

### CODE REVIEW

**Comment by marionleborgne** [comment]
Note about the progress made in this PR: I refactored the experiment runner and its visualizations (and added some new ones). I also added unit tests. With the graphs and the tests, it's now easier to see how the clustering behave. My next step is to roll in new ideas for the clustering algo. I will validate/invalidate my hypothesis based on the graphs (and what I am expecting to see in these graphs)

**Comment by marionleborgne** [comment]
Note 2: The new and clean code for the experiments currently lives in `projects/online_sequence_classification/clustering/new`. When I get to a point where the results of the clustering algo start to be good, I will the appropriate code to `htmresearch/frameworks`. For now I will leave it in `clustering/new`.

**Comment by marionleborgne** [comment]
I cleanup up the code.
* Updated network params with nupic ones
* Updated READMEs
* Restructured project folders

 @ywcui1990 I will merge this PR and close the associated JIRA. The distance metric has been validated and the code is cleaner. Experiments are broken down in phases (generate data -> run HTM network -> run clustering -> visualize) and there are more visualizations of the clustering performance which will make it easier for me to debug and improve the clustering algo. I will open a new PR with these improvements. Merging this now.

**Comment by marionleborgne** [comment]
@rhyolight Why don't I pass the contributor validator? :/ I signed them even before I joined numenta :P

**Comment by marionleborgne** [comment]
@rhyolight I signed them again with my numenta email address. Let's see if I pass the check... I am curious to know why I did not pass the check initially.

**Comment by rhyolight** [comment]
@marionleborgne there have been problems with contributor validation. I'll look into it.

**Comment by marionleborgne** [comment]
@rhyolight Thanks :)

**Pull request merged**
