### PR TITLE
Letter encoder that uses phonetics

### PR DESCRIPTION
**Pull request by akhilaananthram**
Hopefully this letter encoder can be used for speech synthesis or something in the future!  I added a README as well.

@subutai

### CODE REVIEW

**Comment by subutai** [comment]
:fireworks: :+1:

**Comment by cogmission** [comment]
@akhilaananthram Wow this is exciting!

**Comment by akhilaananthram** [comment]
@cogmission: thanks! that was part of my hack for our intern hackathon

**Comment by cogmission** [comment]
@akhilaananthram Nice!

**Comment by rcrowder** [comment]
@akhilaananthram :+1: Thanks you. As soon as I saw this I thought of the label data accompanying spoken sentence data in Mocha-TIMIT (http://data.cstr.ed.ac.uk/mocha/README_v1.2.txt)
https://github.com/rcrowder/nupic.audio/tree/HTMforGenreClassification/HTMforGenreClassification#mocha-timit

**Pull request merged**
