### PR TITLE
Swap TM implementations

### PR DESCRIPTION
**Pull request by oxtopus**
@subutai @ywcui1990 re: #601 and #604

### CODE REVIEW

**Comment by subutai** [comment]
@oxtopus Cool!  Can you reproduce all of the plots in the paper?

**Comment by mrcslws** [comment]
It looks like this change just converts most of the faulty_temporal_memory into dead code, since the new TM doesn't have these phase methods (e.g. `activateCorrectlyPredictiveCells`). Previously these methods were overriding methods on the TM.

I think the task here is to take the functionality of the faulty_temporal_memory and somehow plug it into the new TM. Maybe we'd do this by forking it, or maybe by proposing something else.

Also we don't necessarily have to use the C++ TM.

**Comment by oxtopus** [comment]
@subutai this contains only a simple plot function that displays the accuracies for visual confirmation.  It doesn't produce a pretty plot with the combined results.

**Comment by subutai** [comment]
@oxtopus Oh ok, I thought it was ready for review. We shouldn't merge any changes until we can replicate the previous results. Comments from @mrcslws might be important to consider.

**Comment by oxtopus** [comment]
Here's what I have so far: screen shot 2016-08-25 at 1 36 47 pm

I can't quite figure out why the lines are wide like that, but is this what you had in mind, @subutai ?

**Comment by subutai** [comment]
@oxtopus Yes, that looks very similar but the values are somewhat different. 75% cell death in the paper's figure dropped to about 20% accuracy before going back up. Here it goes down to 35% or so. I really don't understand the 100% cell death scenario and how it go back to perfect performance - ??

Can you also try and replicate Figure 6A as well? http://journal.frontiersin.org/article/10.3389/fncir.2016.00023/full#h4

**Comment by oxtopus** [comment]
@subutai now it's ready for review.  Here are the two plots I generated using the commands in the readme:

figure_6a
figure_6b


Perhaps the difference in values is related to differences in parameters?

**Comment by subutai** [comment]
@oxtopus There should be no differences in parameters. The goal is to replicate the paper findings.

The first plot doesn't look right - it is a high order (multiple cells per col) vs low order (1 cell per col) test, not a cell death test.  There should be no cell death in that one (please see legend on the figure).

I am still worried about the differences in the second cell death plot. What happened to the 100% death plot? Did you simply remove that line, or did you find and fix the underlying issue I was worried about?  It's behavior was an indication to me that there is a problem in the code somewhere.

**Comment by oxtopus** [comment]
I removed the 100%.  I'd added it for my own consideration temporarily and
didn't intend for it to be in final result.  I'll follow up with a fix re:
first order vs high order.

As for results, I swapped out one implementation for another (removed the
phases implementation in favor of the cpp version).  I get different
results from the paper when I revert to the original implementation, too,
so I'm not sure what to say.  I'll check in with you tomorrow in-person to
see what can be done to get the results identical.

**Comment by subutai** [comment]
Sounds good - we can discuss tomorrow.

**Comment by mrcslws** [comment]
The code is never consuming `self.deadCells`.

To do this with today's TM, you'll need to fork it. I thought about it and there's no way to manipulate the `self.activeCells`, etc. to produce correct results. The dealbreaker is `burstColumn`, where it will learn segments on dead cells and you have no way to stop that.

I have an idea for a way we could change the Python TM so that it supports extensibility like this through subclassing. It will make the code slightly slower but that's fine for Python.

Note that subclassing a C++ TM doesn't allow extensibility because the C++ code won't call into the derived class's methods. It's oblivious of them. Maybe this is solvable through SWIG directors, like I did [here](https://github.com/numenta/nupic.core/blob/fc4ed789c0b50be9bd414c4194ac50f90e08959c/src/nupic/bindings/algorithms.i#L1661), but I think we can just stick with Python classes when we extend-through-subclassing.

**Comment by subutai** [comment]
@mrcslws Yes, for experiments like these it is totally fine to subclass from Python, and actually easier to write and debug.

**Pull request closed without merging**
