### PR TITLE
Update UTP to be compatible with C++ SP

### PR DESCRIPTION
**Pull request by chetan51**

### CODE REVIEW

**Comment by chetan51** [comment]
@scottpurdy @subutai I finished adding the necessary methods to the C++ SP bindings [1], and updated the UTP to use those methods (this PR). When I ran the NLP profiling, I found that it was getting worse accuracies, so I added unit tests [2] for all those methods. This helped me find and fix bugs related to data types in the bindings.

Now, I'm seeing that the NLP profiling results are actually producing higher accuracy than with the python SP. I don't know why this is the case, and I'm not sure it's a good thing. In terms of speed, with the C++ SP the profiling task takes only 125 seconds (compared to the python SP's 440 seconds). This is a 3.5x speedup.

Should we be concerned that the results are different with the C++ SP (even though they are better) and investigate? Not sure what the next steps are, or if this task can be marked as complete (after review and merge).

[1] https://github.com/numenta/nupic.core/pull/689
[2] https://github.com/numenta/nupic/pull/2755

**Comment by scottpurdy** [comment]
We should try to see where the difference is coming from. There might be a simple way to remedy the deviation and if not we will need to know why it is different before we decide what to do.

**Comment by subutai** [comment]
I agree with Scott. If you believe your changes should cause no deviations, we should track it down.

**Comment by chetan51** [comment]
I am investigating this discrepancy now.

**Comment by chetan51** [comment]
@scottpurdy @subutai
Here is a status update on this investigation:

- I added unit tests to all new function bindings to ensure the behavior matches the C++ unit tests, and fixed some type casting bugs.
- I started bisecting the code by printing data in the NLP profiling experiment and comparing the printouts of the C++ SP and python SP.
- I isolated a difference in results to the `_inhibitColumns` function. I verified that the input to the function is identical, but the outputs (the list of `activeCells`) varies slightly (one column different for around 8 iterations across the whole experiment) between the two runs.
- So far, I've tried the following changes to try and make the results of `_inhibitColumns` identical:
     - Remove the tie breaker functionality. This actually increased the difference in results.
     - Increase the size of the tie breaker. This reduced the difference in results to a single different column for only 4 iterations.
     - Explicitly specify datatypes of all numpy arrays of floats in `UnionTemporalPooler` and `SpatialPooler` to `float32`. Since some of the arrays were `float64`, and C++ uses 32-bit floats, I thought making them consistent might help. It actually changed the results, but didn't eliminate the discrepancy.

Next, I can try explicitly specifying the datatypes of all numpy arrays of ints to be `uint32`. I'm not sure it will help, but I think we should be consistent in our numpy datatypes anyway. Do you guys have any other ideas on how I can proceed with this investigation?

**Comment by scottpurdy** [comment]
@chetan51 - You should be able to keep bisecting to see exactly where the change happens. Is that possible here?

**Comment by chetan51** [comment]
@subutai @scottpurdy 

Update: I went through and specified datatypes for all unspecified numpy arrays and fixed code in spatial pooler, union temporal pooler, and language sensor. Now they should all be using the same datatypes that are used in C++.

However, the slight discrepancy still exists. I'm going to compare the sums of the python and C++ tie breakers next to look for roundoff errors. This is proving to be more difficult than I thought!

**Comment by chetan51** [comment]
@subutai @scottpurdy 

So you won't believe this.

I verified that the overlaps that are input to the `inhibitColumns` function are identical. Then, I checked the tie breakers. I discovered that the python SP and the C++ SP's tie breakers are actually not identical, there are slight differences due to use of 32-bit or 64-bit floats. [I fixed this difference](https://github.com/chetan51/nupic/commit/baae5f35e773e03f3f9e79c7ae6955a4dd7d8dc4), and verified that they are identical now.

...and yet, the discrepancy remains. Can't believe I actually found a relevant issue and yet fixing it didn't fix the discrepancy!

I double checked it, but I'll triple check my work and compare all the relevant variables now. I feel like I'm still missing something.

**Comment by subutai** [comment]
@chetan51 Interesting. I guess that difference was not sufficient to cause any real tie breaking issues. Nice job in finding that difference, even though it didn't fix all the problems.

**Comment by chetan51** [comment]
@subutai Ready for review after https://github.com/numenta/nupic/pull/2755 is merged.

**Comment by chetan51** [comment]
@subutai @scottpurdy 

Final results:

Both versions of the UTP (using Python SP vs. C++ SP) get identical results now. If you use the C++ SP version, the NLP profiling time drops from around 440 seconds to 150 seconds (almost a 3x improvement). The tie breaker functionality has been removed, and we can now get rid of the tie breaker data in the C++ and Python SPs.

**Comment by subutai** [comment]
@chetan51 You'll need to merge in master into this PR, but otherwise :+1:

**Pull request merged**
