### PR TITLE
IMBU-155: Fluent API tests

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
- Test Imbu lifecycle for all NLP classification models
- Fix and add unit tests for Fluent API responses

### CODE REVIEW

**Comment by BoltzmannBrain** [comment]
@oxtopus @lscheinkman please review.

**Comment by BoltzmannBrain** [comment]
@oxtopus @lscheinkman ping... I would like to get the Imbu build passing again

**Comment by lscheinkman** [comment]
@BoltzmannBrain The tests work for me but I've noticed `model.pkl` has a hardcoded `cacheDir` pointing to your laptop. https://github.com/BoltzmannBrain/nupic.research/blob/fluent_tests/projects/imbu/engine/sample_reviews/CioDocumentFingerprint/model.pkl#L232-L234

Was that intentional?

**Comment by BoltzmannBrain** [comment]
@lscheinkman thank you. Yes that is by design to be handled gracefully: when the model is deserialized it reinstantiates the cortipy client, setting the cache location to the default for the local machine--in docker this is the cache/ dir.

**Pull request merged**
