### PR TITLE
Dialog open with Document+Row Details

### PR DESCRIPTION
**Pull request by brev**
Hi @BoltzmannBrain sorry for the delay.
Quick working example of a Dialog popup, below.
You had all the right React/Flux ideas, it can just be a pain to tie them together initially.

### Code Changes
 
1. Created `stores/dialog.js`, a store to hold Dialog state (open/closed, title, body text, action buttons, etc). This store watches for `DIALOG_OPEN` and `DIALOG_CLOSED` actions to make changes to itself.
1. Updated main `browser/app.js` to get access to new Store
1. Created `actions/dialog-open.js` and `actions/dialog-close.js`, which can be called to fire off `DIALOG_OPEN` and `DIALOG_CLOSED`, which will affect the new Store.
1. Created new MUI React Dialog `components/dialog.jsx`, and set it up to watch for changes on the new Store.  Clicking the default "Close" button at bottom of the Dialog popup will fire `actions/dialog-close.js`.
1. Inject the new Dialog component (open or closed) into the app via `components/main.jsx`.
1. Change the `components/search-results.jsx` component, adding a click handler on each table row. Click will prep the data for display, and fire `actions/dialog-open.js`.

### Click path

1. Click on Table row, `actions/dialog-open` is called, firing `DIALOG_OPEN` with data.
1. New Store catches the Open event, and fills itself with new state/data.
1. Store change triggers observing components to re-render: Results and new Dialog components.
1. Dialog re-renders as Open and Filled with data, based on Store state.
1. Click "Done" on Dialog, and `actions/dialog-close` is called, firing `DIALOG_CLOSE`.
1. New Store catches the Close event......   rinse and repeat!

There's also a few random changes I didn't really mean to save for you (README updates, alphabetizations, code style tweak, etc.) Feel free to use or ignore. :)

I think that's it, please let me know of any questions.
thanks

### CODE REVIEW

**Comment by brev** [comment]
**DEMO.** Please do not merge!

**Comment by BoltzmannBrain** [comment]
@brev this is great, immensely helpful! Yes tying the pieces together is the tricky part. Thank you for making this all so much more clear. I've edited and merged #541 to work with this PR. Are you okay if we just merge this PR and then I can open a new one for additional changes (including tests)?

**Comment by brev** [comment]
@BoltzmannBrain please do! thanks

**Comment by BoltzmannBrain** [comment]
@brev can you please merge master to resolve the conflicts?

**Comment by brev** [comment]
@BoltzmannBrain 👍

**Pull request merged**
