### PR TITLE
Normalize Imbu scores for word-level models

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
Normalize results to accommodate for multiple tokens in queries (https://jira.numenta.com/browse/RES-178).
@subutai merging to test Imbu.

### CODE REVIEW

**Comment by subutai** [comment]
@BoltzmannBrain This won't affect the order of the results, will it?

**Comment by BoltzmannBrain** [comment]
Nope. The query() method in this class gets unsorted results from the classification model and the formatResults() method doesn't do any sorting, so the client (Imbu API) is responsible for sorting.

**Comment by subutai** [comment]
Don't we sort results in classification model if sortResults=True?

**Comment by BoltzmannBrain** [comment]
Yes, Imbu specifies sortResults=True. Leaving the results unsorted allows us to pass less information between the ImbuModels class and the Imbu API, speeding up the models.

**Pull request merged**
