### PR TITLE
Custom Record Sensor region 

### PR DESCRIPTION
**Pull request by marionleborgne**
Created a custom sensor region sub-classing `RecordSensor.py` and that offers additional functionalities:
-  Ability to stop using the RecordStream as the source of input data.
-  Ability to set the next record timestamp, value, and category manually.

@subutai As I mentioned I am using this to be able to have the flexibility to read data from a file and/or to also feed data manually to the region (in my case with RabbitMQ). My use case is that once the network has been primed with the training data contained in the CSV file passed to `RecordSensor` as an `RecordStream`, I stop using this as data source, and start feeding data manually. (I am likely to turn learning off for all regions at that point too, but it's anecdotal)

To make the subclassing of `RecordSensor.py` nicer, I refactored it slightly and created a PR to nupic here: https://github.com/numenta/nupic/pull/3012

I made sure that I get the same results with the new `CustomRecordSensor.py` by creating a unit test called `test_custom_sensor_region_classification.py`

cc @subutai @rhyolight

### CODE REVIEW

**Comment by marionleborgne** [comment]
After pulling from upstream master, I had to comment out some lines that were added to link the classifier region. There is an if statement that seems to be always true (at line 325) and broke some of the classification network unit tests: `network.regions[regionName].getSpec()` returns a Swig object of type `nupic::Spec *` and when `.contains("partitionIn")` is being run, this always returns `true`. This is resulting in the execution of the nested block of code: 
```
    network.link(sensorRegionName, regionName, "UniformLink", "",
                 srcOutput="sequenceIdOut", destInput="partitionIn")
```
which is messing up the network classification results (expected: 100% accuracy on a trivial classification test VS actual: 41.67 % ).  @BoltzmannBrain I am actually unclear about what this block of code that was added is supposed to do, do you know?

```
  # Link in sequenceId/partitionId if the appropriate input exists
  classifierSpec = network.regions[regionName].getSpec()
  if classifierSpec.inputs.contains('partitionIn'):
    network.link(sensorRegionName, regionName, "UniformLink", "",
                 srcOutput="sequenceIdOut", destInput="partitionIn")
```

**Comment by BoltzmannBrain** [comment]
@marionleborgne it's returning True likely b/c all the regions you're testing have the `partitionIn` link. We added the "sequenceId/partitionId" linkage so we know what sequence is currently running when inspecting a given region. The block of code for adding the link to the classifier is needed b/c the classifier doesn't use `_linkRegions()` like the others regions before it. This should not affect any test results.

**Comment by BoltzmannBrain** [comment]
Your reason for creating this subclass -- manually feed in data -- is useful functionality, which we've incorporated into LanguageSensor in a different way (a record queue in the region's `compute()`). It may be a good idea to add this to the RecordSensor in NuPIC. @subutai @scottpurdy what do you think?

**Comment by scottpurdy** [comment]
The current RecordSensor lets you specify a `dataSource` that can be any RecordStream subclass. So if you want to manually pass data then set `dataSource` to an object that you manually pass data to.

I don't think the two methods that you guys describe make sense:

- I think region parameters are intended as region constructor parameters, not iteration-by-iteration values passed in.
- The compute method is called by the network so you wouldn't be able to set some arbitrary parameter. Better to stick to the interface.

One way that we might be able to make this easier is by giving Network objects a native way to set the value for a region's input. That way the region doesn't care if the input is coming from another region or from the client and we don't have to jump through hoops to get data into regions.

**Comment by subutai** [comment]
> I think region parameters are intended as region constructor parameters, not iteration-by-iteration values passed in.

I haven't had time to look through the full code, but calling set/get parameters on an iteration by iteration basis is perfectly fine (i.e. it's not just for constructor parameters). It might make sense particularly for a sensor region as a simple way to pass in data from external live sources.  It is definitely much better than using getSelf(), etc which is not compatible across languages.

**Comment by marionleborgne** [comment]
This is an old PR that is obsolete now. I'm closing it.

**Pull request closed without merging**
