### PR TITLE
IMBU-104: Add dataset support

### PR DESCRIPTION
**Pull request by lscheinkman**
@BoltzmannBrain This PR is for both IMBU-104 and IMBU-105.

### CODE REVIEW

**Comment by BoltzmannBrain** [comment]
:+1: but found some related bugs that should be resolved with a followup PR.

**Comment by BoltzmannBrain** [comment]
@lscheinkman trying to fix the fluent unit tests (IMBU-156) I reverted back to 7f40574 to see if the test pass and they don't. Any ideas why? for `TestFluentAPI.testDatasetList()` it appears fluent's `DatasetHandler` is never queried.

**Comment by lscheinkman** [comment]
@BoltzmannBrain It worked from the the `docker` container.
```
root@7a067a6a0820:/opt/numenta/nupic.research# py.test tests/imbu              
============================= test session starts ==============================
platform linux2 -- Python 2.7.6 -- pytest-2.5.1
plugins: cov, xdist
collected 17 items / 1 skipped 

tests/imbu/unit/fluent_api_test.py ......s.
tests/imbu/unit/imbu_models_test.py .........

==================== 16 passed, 2 skipped in 57.13 seconds =====================
```

**Comment by BoltzmannBrain** [comment]
@lscheinkman hmm can you try running it locally?

**Pull request merged**
