### PR TITLE
Reorganization of `imagenet` project.

### PR DESCRIPTION
**Pull request by mvacaporale**
* Move `imagenet_experiment` to `frameworks/pytorch`
* Remove `imagenet` project.

### CODE REVIEW

**Comment by mvacaporale** [comment]
> Other than moving imagenet_experiment.py to frameworks/pytorch/imagenet_experiment.py, we should keep the rest of the experiments in the project folder. Just make a copy into your other repo.

@subutai It's in the other repo. I just requested you to review it.

**Comment by subutai** [comment]
> @subutai It's in the other repo. I just requested you to review it.

I saw that. I'm just saying don't delete the files here.

**Comment by mvacaporale** [comment]
> > @subutai It's in the other repo. I just requested you to review it.
> 
> I saw that. I'm just saying don't delete the files here.

So I should leave a second copy in `nupic.research`?

**Comment by subutai** [comment]
> > > @subutai It's in the other repo. I just requested you to review it.
> > 
> > 
> > I saw that. I'm just saying don't delete the files here.
> 
> So I should leave a second copy in `nupic.research`?

yes.

**Comment by mvacaporale** [comment]
> > > > @subutai It's in the other repo. I just requested you to review it.
> > > 
> > > 
> > > I saw that. I'm just saying don't delete the files here.
> > 
> > 
> > So I should leave a second copy in `nupic.research`?
> 
> yes.

Will do

**Comment by mvacaporale** [comment]
@subutai Readded `nupic.research.projects.imagenet`

**Comment by subutai** [comment]
Please also update imagenet_tune so it correctly imports ImagenetExperiment

**Comment by mvacaporale** [comment]
> Please also update imagenet_tune so it correctly imports ImagenetExperiment

Good point, updated. See last commit.

**Pull request merged**
