### PR TITLE
LSTM optimizations

### PR DESCRIPTION
**Pull request by chetan51**
Fixes memory pressure issue, and speeds up inference.

### CODE REVIEW

**Comment by chetan51** [comment]
cc: @subutai @ywcui1990

**Comment by ywcui1990** [comment]
@chetan51 Could you explain what is the origin of the memory problem? and why does this fix work?

**Comment by chetan51** [comment]
It was actually an optimization to the way I was running the LSTM network. Before this change, during the inference step (no learning) I was feeding the entire history to the network for each time step (due to a bug in my code). Since LSTM stores the history, this resulted in O(n^2) memory usage. After this change, I just give the latest element to the network on each time step, and only feed the entire history when the network is retrained (every 667 iterations). This makes the memory usage of LSTM into O(n), and speeds up the inference stage.

**Comment by chetan51** [comment]
I have yet to confirm that this change doesn't hurt accuracy of the model, since it changes what is being fed to the model at each time step (just the latest element, rather than the entire history). So far the results look consistent.

**Comment by ywcui1990** [comment]
So the pyBrain LSTM stores the history even with learning turned off? I am
concerned that the inference stage might interfere with learning since it
changed the state of the network.

**Comment by chetan51** [comment]
Yes, see [Using Recurrent Networks](http://pybrain.org/docs/tutorial/netmodcon.html#using-recurrent-networks).

For learning, I discard the network and train a new one, so there shouldn't be any such interference.

**Comment by ywcui1990** [comment]
Thanks for the explanation. It makes sense to me now.

**Pull request merged**
