### PR TITLE
RES-2082 Move to use of sparsity parameter

### PR DESCRIPTION
**Pull request by lspracklen**

### CODE REVIEW

**Review by subutai — APPROVED** [review]
Looks good to me. You'll probably need to merge in the latest from master into this PR, before you can merge the PR itself.

**Comment by lscheinkman** [comment]
@subutai Should we also deprecate the `weight_sparsity` parameter passed to this function?
https://github.com/lspracklen/nupic.research/blob/d18ada3f56246f299508e41ec33b1a5bbe591e3f/nupic/research/frameworks/pytorch/models/le_sparse_net.py#L44

**Comment by subutai** [comment]
> @subutai Should we also deprecate the `weight_sparsity` parameter passed to this function?
> https://github.com/lspracklen/nupic.research/blob/d18ada3f56246f299508e41ec33b1a5bbe591e3f/nupic/research/frameworks/pytorch/models/le_sparse_net.py#L44

Not sure it's worth changing this file per se. This function has a lot of old baggage, such as consolidated weights. If it's useful, we could create a simpler, clean version of this and put it into nupic.torch as an example module.

**Comment by renderist** [comment]
Are we making a pass through the sources to correct the cases when we used weight_sparsity we really meant
density, and fixing the code so that weight_sparsity actually means sparsity of weights?

Kevin


On Mar 26, 2021, at 5:28 PM, Luiz Scheinkman ***@***.******@***.***>> wrote:



@subutai<https://github.com/subutai> Should we also deprecate the weight_sparsity parameter passed to this function?
https://github.com/lspracklen/nupic.research/blob/d18ada3f56246f299508e41ec33b1a5bbe591e3f/nupic/research/frameworks/pytorch/models/le_sparse_net.py#L44

**Comment by subutai** [comment]
> Are we making a pass through the sources to correct the cases when we used weight_sparsity we really meant density, and fixing the code so that weight_sparsity actually means sparsity of weights?

That's a big job. Not sure it's worth it. All new Vernon based code and later should hopefully just use `sparsity`.

**Pull request merged**
