### PR TITLE
Debug opf

### PR DESCRIPTION
**Pull request by subutai**

### CODE REVIEW

**Comment by subutai** [comment]
@ywcui1990 The debug script was incorrectly getting output information. I have updated the debug script to get encoded output data correctly, and it always seems to match the SP inputs.  In other words, there is indeed a difference in encoded outputs between the two files

The proper way to look at the output of a region is to look at its named outputs and use the Network API calls to get those values, as shown in the modified script. 

The RecordSensor region also computes its own internal values using the encoded information, confusingly calls it "_outputValues" and includes a method called getOutputValues() to get those. However, this is an internal variable that is *not* exactly what is sent to the SP. I realize this is confusing - I am not sure why it is written like that.

Line 331 of RecordSensor shows the actual call to encode:
```
self.encoder.encodeIntoArray(data, outputs["dataOut"])
```
The Network API output called "dataOut" will now contain the output of the region. That is simple.

Lines 337 to 348 then create _outputValues from dataOut - there must be an off-by-one bug in that logic.  I don't know everywhere this is used, but I do see that clamodel.py uses it in line 447. Someone should track down this off-by-one bug and fix it in RecordSensor.

@scottpurdy - Not sure who to assign this to, but there is a bug in RecordSensor, probably somewhere in the above lines.  Also, that sensor could really be cleaned up and simplified.

**Comment by scottpurdy** [comment]
@subutai just to clarify, you are asking for someone to review this PR and then also suggesting we have someone look into the RecordSensor bug?

**Comment by subutai** [comment]
@scottpurdy Just to look into the RecordSensor bug.  Not necessary to review this PR.

**Comment by scottpurdy** [comment]
Kk sounds like a good intern starter task for Monday

**Pull request closed without merging**
