### PR TITLE
Change knn distance metric to the new pctOverlapOfInput

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
relies on [nupic #2713](https://github.com/numenta/nupic/pull/2713)

### CODE REVIEW

**Comment by subutai** [comment]
Why do we want to use pct overlap instead of raw overlap?

**Comment by BoltzmannBrain** [comment]
For example, an input of 40 ON bits could have raw overlaps of 38, 19, 13, 1, 0, ... For the classification experiments this is fine. For imbu however, these "scores" would confuse the user, especially when one queried input is 40 ON bits and the next could be 120.

**Comment by subutai** [comment]
I'm not sure I understand. We should make sure the score reflects what we actually use (which is raw overlap) otherwise you would get a sorted list where the score is non-monotonic.  You can always normalize the score before displaying but that shouldn't affect the KNN.

**Comment by BoltzmannBrain** [comment]
We're using the distance metric to calculate the distance between a test input and the trained-on prototypes, in the classification experiments and in imbu. Anything the model does with the distances calculated for one input is independent of anything it does with the distances calculated for another input. The sorted list is specific to the one input under test, so the score will be monotonic whether it is raw overlap, or raw overlap divided by the size of the input (i.e. `pctOverlapOfInput `).

**Comment by BoltzmannBrain** [comment]
@subutai please review. I switched back to using rawOverlap in the KNN and then normalizing the distances after the fact; I think this is a little less confusing.

**Comment by BoltzmannBrain** [comment]
@scottpurdy Subutai may have left for his vacation, so please take a look.

**Comment by BoltzmannBrain** [comment]
Merging to keep working on imbu.

**Pull request merged**
