### PR TITLE
Introduce the Omniglot dataset via git-lfs

### PR DESCRIPTION
**Pull request by mvacaporale**
This PR adds the downloaded Omniglot dataset to our testing directory. This will be helpful for more extensive testing of our experiment framework Vernon such as end-to-end tests of the experiment classes.

### CODE REVIEW

**Review by lscheinkman — CHANGES_REQUESTED** [review]
To keep the number of files in github manageable, you should only keep the zip file in `git lfs`. It could be easily done by creating a torchvision dataset on top of `zipfile.ZipFile`

**Comment by subutai** [comment]
Why are we adding the entire dataset into the repo? That's way too much to have in our codebase. For unit tests we should at most add a handful of files - that should be sufficient for any functionality testing.

**Comment by mvacaporale** [comment]
@subutai What are your thoughts on adding just the zip files? This is of course the entire dataset, but relatively much more manageable. I'd like to add the Omniglot dataset specifically to include tests for the `create_*_loader` methods and the `create_*_sample` methods. As well, I believe a small dataset such as Omniglot or MNIST will enable more end-to-end testing of our experiment classes, which I believe we've lacked up to now.

**Comment by mvacaporale** [comment]
I've closed this PR for a new one that just includes the zip files:
https://github.com/numenta/nupic.research/pull/392

**Pull request closed without merging**
