### PR TITLE
LanguageSensor region for NLP experiments, and integration with ClassificationNetwork

### PR DESCRIPTION
**Pull request by BoltzmannBrain**

### CODE REVIEW

**Comment by BoltzmannBrain** [comment]
@marionleborgne please review. Changes here allow us to run NLP experiments through the classification network, and changes to classify_active_cells.py shouldn't affect your "white noise" experiment.

**Comment by BoltzmannBrain** [comment]
@marionleborgne ping :smile:

**Comment by BoltzmannBrain** [comment]
PING :smile_cat:

**Comment by BoltzmannBrain** [comment]
@marionleborgne :grimacing:

**Comment by tomsilver** [comment]
@marioleborgne test

**Comment by tomsilver** [comment]
test without my name

**Comment by tomsilver** [comment]
@marionleborgne real test

**Comment by marionleborgne** [comment]
@tomsilver  thanks :grin:

**Pull request merged**
