### PR TITLE
Move tests from projects/imbu/tests to tests/

### PR DESCRIPTION
**Pull request by oxtopus**

### CODE REVIEW

**Comment by BoltzmannBrain** [comment]
@oxtopus the tests don't pass...

**Comment by oxtopus** [comment]
They fail for me, too, but for what appears to be a version incompatibility between nupic and nupic.core and not specific to this change.

**Comment by BoltzmannBrain** [comment]
@oxtopus test pass and I see you've closed the jira... good to merge?

**Comment by oxtopus** [comment]
About to...

**Pull request merged**
