### PR TITLE
RES-1481: Refactor ImagenetExperiment to maintains the current epoch number internally

### PR DESCRIPTION
**Pull request by lscheinkman**
In order to make the checkpoints self contained we need to keep the current epoch as part of the `ImagenetExperiment` instead of ray tune or any other external framework

### CODE REVIEW

**Comment by lscheinkman** [comment]
> I think we also need something in imagenet_experiment's run_epoch that tells imagenet_tune to stop based on the epoch. We should put a stop criterion that's based on self.epoch==self.epochs, and then that should be specified in the stop_criterion in imagenet_tune.

Correct, but that will be in a separate PR. See RES-1480

**Comment by subutai** [comment]
> > I think we also need something in imagenet_experiment's run_epoch that tells imagenet_tune to stop based on the epoch. We should put a stop criterion that's based on self.epoch==self.epochs, and then that should be specified in the stop_criterion in imagenet_tune.
> 
> Correct, but that will be in a separate PR. See RES-1480

Ok, got it.

**Comment by subutai** [comment]
> One small comment. Should we make self.epoch to be self.current_epoch? Confusing with self.epoch and self.epochs.

Alternatively we could rename self.epochs

**Comment by lscheinkman** [comment]
> > One small comment. Should we make self.epoch to be self.current_epoch? Confusing with self.epoch and self.epochs.
> 
> Alternatively we could rename self.epochs

Ray tune and some of the mixins refers to the `epoch` as `iteration`.

What do you prefer? `self.epochs => self.num_epochs` or `self.epoch => self.current_epoch` or `self.epoch => self.iteration` ?

**Comment by subutai** [comment]
> > > One small comment. Should we make self.epoch to be self.current_epoch? Confusing with self.epoch and self.epochs.
> > 
> > 
> > Alternatively we could rename self.epochs
> 
> Ray tune and some of the mixins refers to the `epoch` as `iteration`.
> 
> What do you prefer? `self.epochs => self.num_epochs` or `self.epoch => self.current_epoch` or `self.epoch => self.iteration` ?

I don't like iteration for ImagnetExperiment - iteration is too general (which makes sense for Ray). Epoch is more specific to training in networks and widely used in ML.  I'm fine with either of your first two suggestions! Maybe the first one is easier and smaller changes all around.

**Pull request merged**
