### PR TITLE
Add Saleem paper and Rauschecker paper on where/what pathway in auditory...

### PR DESCRIPTION
**Pull request by ywcui1990**
@subutai 
I added two references to the bibliography
- Saleem paper on integration of visual and locomotion signals in V1
- Rauschecker paper on where/what pathway in the auditory system

### CODE REVIEW

**Comment by subutai** [comment]
:+1:

**Comment by rcrowder** [comment]
@ywcui1990 As a compliment to the Rauschecker paper (?), I'd recommend Catherine Carr's paper entitled "Processing of Temporal Information in the Brain" DOI: 10.1146/annurev.en.16.030193.001255  I have a copy in Mendeley, but unsure how to link to it.

**Comment by ywcui1990** [comment]
@rcrowder Thanks for the reference. I am familiar with Catherine Carr's work on temporal coding. It is less relevant to us because her work focused on the early subcortical processing in the brainstem, rather than in the cortex. But you are right it is an important compliment to the Rauschecker paper, which talks about separate processing of spatial locations and auditory patterns in the cortex.  It is important to note that the separation of "where" and "what" pathway in the auditory domain already starts at the subcortical level, which is quite different in the visual system.

**Comment by rcrowder** [comment]
@ywcui1990 Yes, I like [Troy Hackett's](http://www.audiology.org/sites/default/files/journal/JAAA_19_10_04.pdf) 2008 paper (doi: 10.3766/jaaa.19.10.5) outlining anatomical organization. My reading has currently been interrupted by Gordon Shepherd's book on synaptic organization, do need to head back to Donata Oertel and co. book "Integrative functions in the mammalian auditory pathway". Plus more recent discoveries.

**Pull request merged**
