### PR TITLE
Optional recordstream

### PR DESCRIPTION
**Pull request by subutai**
Make FileRecordStream optional for LanguageSensor.
Added method addDataToQueue() to formalize adding data to internal queue.
Removed some unused lines in LanguageSensor.

### CODE REVIEW

**Comment by subutai** [comment]
@BoltzmannBrain

**Comment by BoltzmannBrain** [comment]
@subutai it's not clear to me this works yet. Did you mean to include add'l changes, perhaps using the new `addDataToQueue()` method?

**Comment by subutai** [comment]
@BoltzmannBrain The main change is to add `addDataToQueue`. `ClassificationModelHTM` works if you pass in None for `inputFilePath` in the sense that it does not crash. It does not yet use the `addDataToQueue` method.

**Comment by BoltzmannBrain** [comment]
:+1:

**Pull request merged**
