### PR TITLE
Wall avoidance and SDR tuning

### PR DESCRIPTION
**Pull request by tomsilver**
@chetan51 Please review. Thanks!

### CODE REVIEW

**Comment by tomsilver** [comment]
one thing that we might want to change is that the override can lead to the car hugging the wall at like a 91 degree angle, and userControl won't take over until the car is sufficiently far from the wall. so one option would be to somehow allow the userControl to move away from the wall but not towards it, but giving userControl "partial control" could get messy.

**Comment by chetan51** [comment]
Talked with Tom in person, he is revising the algorithm.

**Comment by tomsilver** [comment]
@chetan51 added files for collecting and comparing depth SDRs. now returning to wall avoidance.

**Comment by chetan51** [comment]
In addition to the suggestions we talked about in person, can you move the logic for capturing screenshot / marking `collectKeyPressed` to a separate script? We might want to use multiple SweepSensors in the future so it should remain clean of screenshotting functionality.

**Comment by tomsilver** [comment]
@chetan51 let me know how the wall avoidance works for you now

**Comment by cogmission** [comment]
BAM! Ouch! Not working so well for me so far... :P   (just kidding)

On Wed, Jun 17, 2015 at 11:58 AM, tomsilver <notifications@github.com>
wrote:

> @chetan51 <https://github.com/chetan51> let me know how the wall
> avoidance works for you now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/numenta/nupic.research/pull/183#issuecomment-112876682>
> .
>



-- 
*With kind regards,*

David Ray
Java Solutions Architect

*Cortical.io <http://cortical.io/>*
Sponsor of:  HTM.java <https://github.com/numenta/htm.java>

d.ray@cortical.io
http://cortical.io

**Pull request closed without merging**
