### PR TITLE
[RES-327] visualize TM / UP states against input data & labels

### PR DESCRIPTION
**Pull request by ywcui1990**
@marionleborgne  Please review

Here is the figure I got. The visualization does reveal several problems of the classification network. The active TM cells are all empty somehow, and the active TP cells don't seem correct. Nevertheless, the visualization script is there. 

image

### CODE REVIEW

**Comment by ywcui1990** [comment]
@marionleborgne I have activeCell trace now after the fix (https://github.com/numenta/nupic/pull/3303). 

Below is an updated figure

image

**Comment by marionleborgne** [comment]
If i use `fileName = 'results/traces_sp-True_tm-True_tp-False.csv'` then I am able to circumvent the file size error. It doesn't crash but the plot does not display

**Comment by ywcui1990** [comment]
@marionleborgne 

I made a few changes to the plotting scripts
* The plots will stay on (I turned off interactive plotting)
* Generate 3 separate plots, one for each trace
* The script takes two parameters, the trace filename and the x-axis range (Example usage: python plot_experiment_result.py --xlim "1700,1750")
* randomize cell orders to visualize high-order effect (cells within the same columns are not close to each other on the graph).

**Comment by marionleborgne** [comment]
👍 Thanks @ywcui1990

**Pull request merged**
