### PR TITLE
Clarify that code will not be bug free

### PR DESCRIPTION
**Pull request by fredsa**
Restore original intent of code quality statement

### CODE REVIEW

**Comment by subutai** [comment]
😃 Haha - that's a good catch. 

In order to for us to merge your PR, you would need to sign the Contributor's License: https://numenta.org/licenses/contrib/

(If that doesn't work for you, I can just make this change myself, but it would be nicer to include your commit.)

**Comment by fredsa** [comment]
Done! Glad my first contribution is so meta: help make the code more bug free in a comment about it being not bug free!

As an aside: thank you to the entire Numenta team for taking this radically open approach. Love watching the research meetings and paper reviews. This is absolutely how everyone who wants to further a field should do this!

(Minor nit: slightly better room (multi) mic setup would be greatly appreciated. Sometimes hard to hear. I listen in on my drive to work, often 2x speed.)

**Comment by subutai** [comment]
Great! Thank you so much for the comments - it means a lot. I know Matt is constantly trying to improve the mic setup. 

@rhyolight - can you install his signed license and approve the PR?

**Comment by rhyolight** [comment]
I have processed the contributor license. Hoping this comment will jog the CI process...

**Pull request merged**
