### PR TITLE
Better use and documentation of resets in NLP docfp model

### PR DESCRIPTION
**Pull request by BoltzmannBrain**
Review from previous PR (#503)[here](https://github.com/numenta/nupic.research/pull/503#discussion_r60267877)

### CODE REVIEW

**Comment by BoltzmannBrain** [comment]
@oxtopus I've made the `reset` name more clear. We use 0/1 for the reset value because the Network API defines `reset` as Real32.

**Comment by BoltzmannBrain** [comment]
@oxtopus @subutai please take a look

**Comment by oxtopus** [comment]
:+1:

**Comment by subutai** [comment]
👍

**Pull request merged**
